# Generated by Django 6.0.2 on 2026-05-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
