# Generated by Django 6.0.2 on 2026-05-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_vacancy_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_irrelevant',
            field=models.BooleanField(default=False),
        ),
    ]
