# Generated by Django 6.0.2 on 2026-10-04 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_vacancy_is_sent_vacancy_is_irrelevant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('is_irrelevant', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.CharField(choices=[('Jooble.ua', 'Jooble'), ('Robota.ua', 'Robota.ua'), ('Work.ua', 'Work.ua'), ('DOU.ua', 'DOU.ua')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['source', '-created_at'], name='jobs_vacanc_source_f3646f_idx'),
        ),
        migrations.AddField(
            model_name='uservacancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='jobs.vacancy'),
        ),
        migrations.AddIndex(
            model_name='uservacancy',
            index=models.Index(fields=['user', 'applied', 'is_irrelevant'], name='jobs_userva_user_id_4ebff2_idx'),
        ),
        migrations.AddConstraint(
            model_name='uservacancy',
            constraint=models.UniqueConstraint(fields=('user', 'vacancy'), name='unique_user_vacancy'),
        ),
    ]
