# Generated by Django 6.0.2 on 2026-10-04 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_uservacancy_alter_vacancy_options_alter_vacancy_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Jooble.ua', 'Jooble'), ('Robota.ua', 'Robota.ua'), ('Work.ua', 'Work.ua'), ('DOU.ua', 'DOU.ua')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('days', models.PositiveSmallIntegerField(default=7)),
                ('keyword', models.CharField(blank=True, max_length=50)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='jobs_parser_source_bae361_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('source',), name='one_running_parse_per_source')],
            },
        ),
    ]
