# Generated by Django 6.0.2 on 2026-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_parserun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserun',
            name='status',
            field=models.CharField(choices=[('running', 'Виконується'), ('success', 'Успішно'), ('failed', 'Помилка')], default='running', max_length=10),
        ),
    ]
